[workspace]
members = ["birthday_problem", "divisors", "arithmetics", "primefactors", "primes", "ordered_words", "file_utils", "sine_wave", "day_of_the_week", "two_sum", "word_frequency", "descramble", "words_from_neighbor_ones"]
resolver = "2"
